/*! Achordeon - MIT License

Copyright (c) 2017 Wolf Robben

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
!*/
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Achordeon.Shell.Wpf.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Achordeon.Shell.Wpf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About Achordeon ähnelt.
        /// </summary>
        public static string AboutTooltip {
            get {
                return ResourceManager.GetString("AboutTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About Achordeon... ähnelt.
        /// </summary>
        public static string AboutWindowTitle {
            get {
                return ResourceManager.GetString("AboutWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The application cannot run the file &apos;{0}&apos;. ähnelt.
        /// </summary>
        public static string CannotRunFile {
            get {
                return ResourceManager.GetString("CannotRunFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The application cannot save the file &apos;{0}&apos;. ähnelt.
        /// </summary>
        public static string CannotSaveFile {
            get {
                return ResourceManager.GetString("CannotSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chord font ähnelt.
        /// </summary>
        public static string ChordFont {
            get {
                return ResourceManager.GetString("ChordFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chord font size ähnelt.
        /// </summary>
        public static string ChordFontSize {
            get {
                return ResourceManager.GetString("ChordFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chord grid size (mm) ähnelt.
        /// </summary>
        public static string ChordGridSizeMm {
            get {
                return ResourceManager.GetString("ChordGridSizeMm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chord Pro files (*.pro)|*.pro ähnelt.
        /// </summary>
        public static string ChordProFileDialogFilter {
            get {
                return ResourceManager.GetString("ChordProFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Marks the selected text to be a chorus, or removes the marks ähnelt.
        /// </summary>
        public static string ChorusUnchorusSelectionTooltip {
            get {
                return ResourceManager.GetString("ChorusUnchorusSelectionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Closes the current view ähnelt.
        /// </summary>
        public static string CloseButtonTooltip {
            get {
                return ResourceManager.GetString("CloseButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Converts the selected text to a comment, or back to plain text ähnelt.
        /// </summary>
        public static string CommentUncommentSelectionTooltip {
            get {
                return ResourceManager.GetString("CommentUncommentSelectionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copies the current selection to the clipboard ähnelt.
        /// </summary>
        public static string CopyButtonTooltip {
            get {
                return ResourceManager.GetString("CopyButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Copy ähnelt.
        /// </summary>
        public static string CopyMenu {
            get {
                return ResourceManager.GetString("CopyMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cuts the current selection to the clipboard ähnelt.
        /// </summary>
        public static string CutButtonTooltip {
            get {
                return ResourceManager.GetString("CutButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cu_t ähnelt.
        /// </summary>
        public static string CutMenu {
            get {
                return ResourceManager.GetString("CutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Draw chord grids ähnelt.
        /// </summary>
        public static string DrawChordGrids {
            get {
                return ResourceManager.GetString("DrawChordGrids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {t:New Song}
        ///{st:Composer Name}
        ///{c:1.)} ähnelt.
        /// </summary>
        public static string EmptyFileTemplate {
            get {
                return ResourceManager.GetString("EmptyFileTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatic updates ähnelt.
        /// </summary>
        public static string EnableAutoUpdates {
            get {
                return ResourceManager.GetString("EnableAutoUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Something went terribly wrong. ähnelt.
        /// </summary>
        public static string ErrorDialogHeader {
            get {
                return ResourceManager.GetString("ErrorDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Achordeon encountered an error... ähnelt.
        /// </summary>
        public static string ErrorDialogTitle {
            get {
                return ResourceManager.GetString("ErrorDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The plain text could not be imported. ähnelt.
        /// </summary>
        public static string FailedToConvertPlainText {
            get {
                return ResourceManager.GetString("FailedToConvertPlainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to convet the selection. ähnelt.
        /// </summary>
        public static string FailedToConvertTheSelection {
            get {
                return ResourceManager.GetString("FailedToConvertTheSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Adjusts the zoom to display the full height of page ähnelt.
        /// </summary>
        public static string FitToHeightToolTip {
            get {
                return ResourceManager.GetString("FitToHeightToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Adjusts the zoom to display the whole page ähnelt.
        /// </summary>
        public static string FitToPageToolTip {
            get {
                return ResourceManager.GetString("FitToPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Adjusts the zoom to display the full width of page ähnelt.
        /// </summary>
        public static string FitToWidthToolTip {
            get {
                return ResourceManager.GetString("FitToWidthToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Global Settings ähnelt.
        /// </summary>
        public static string GlobalSettings {
            get {
                return ResourceManager.GetString("GlobalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Opens the global settings dialog ähnelt.
        /// </summary>
        public static string GlobalSettingsButtonTooltip {
            get {
                return ResourceManager.GetString("GlobalSettingsButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Achordeon global settings dialog ähnelt.
        /// </summary>
        public static string GlobalSettingsTooltip {
            get {
                return ResourceManager.GetString("GlobalSettingsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Home ähnelt.
        /// </summary>
        public static string HomeButtonTitle {
            get {
                return ResourceManager.GetString("HomeButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Welcome to Achordeon! ähnelt.
        /// </summary>
        public static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Interpretes the selected text als ASCII with chords written on top of each line, and converts it to ChordPro format ähnelt.
        /// </summary>
        public static string ImportPlainTextButtonTooltip {
            get {
                return ResourceManager.GetString("ImportPlainTextButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die License: ähnelt.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lyrics only: ähnelt.
        /// </summary>
        public static string LyricsOnly {
            get {
                return ResourceManager.GetString("LyricsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enables the &quot;lyrics only&quot; mode where chords are omitted in the output ähnelt.
        /// </summary>
        public static string LyricsOnlyModeTooltip {
            get {
                return ResourceManager.GetString("LyricsOnlyModeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Achordeon ähnelt.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file {0} does not exists. ähnelt.
        /// </summary>
        public static string MissingFileBody {
            get {
                return ResourceManager.GetString("MissingFileBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File missing ähnelt.
        /// </summary>
        public static string MissingFileHeader {
            get {
                return ResourceManager.GetString("MissingFileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Song ähnelt.
        /// </summary>
        public static string NewSong {
            get {
                return ResourceManager.GetString("NewSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Let&apos;s write another song ähnelt.
        /// </summary>
        public static string NewSongButtonTooltip {
            get {
                return ResourceManager.GetString("NewSongButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Open ähnelt.
        /// </summary>
        public static string OpenFileMenu {
            get {
                return ResourceManager.GetString("OpenFileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Song ähnelt.
        /// </summary>
        public static string OpenSong {
            get {
                return ResourceManager.GetString("OpenSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open a song from a file ähnelt.
        /// </summary>
        public static string OpenSongButtonTooltip {
            get {
                return ResourceManager.GetString("OpenSongButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Operations ähnelt.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Page size ähnelt.
        /// </summary>
        public static string PageSize {
            get {
                return ResourceManager.GetString("PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pastes the current clipboard content to the song editor ähnelt.
        /// </summary>
        public static string PasteButtonTooltip {
            get {
                return ResourceManager.GetString("PasteButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Paste ähnelt.
        /// </summary>
        public static string PasteMenu {
            get {
                return ResourceManager.GetString("PasteMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PDF ähnelt.
        /// </summary>
        public static string PDF {
            get {
                return ResourceManager.GetString("PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Pin to list ähnelt.
        /// </summary>
        public static string PinFileMenu {
            get {
                return ResourceManager.GetString("PinFileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pin this item to the list. ähnelt.
        /// </summary>
        public static string PinToolTip {
            get {
                return ResourceManager.GetString("PinToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plain text ähnelt.
        /// </summary>
        public static string PlainText {
            get {
                return ResourceManager.GetString("PlainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preview ähnelt.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preview mode: ähnelt.
        /// </summary>
        public static string PreviewMode {
            get {
                return ResourceManager.GetString("PreviewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prints the current song ähnelt.
        /// </summary>
        public static string PrintButtonTooltip {
            get {
                return ResourceManager.GetString("PrintButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recent files ähnelt.
        /// </summary>
        public static string RecentFiles {
            get {
                return ResourceManager.GetString("RecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reverts the last undo ähnelt.
        /// </summary>
        public static string RedoButtonTooltip {
            get {
                return ResourceManager.GetString("RedoButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Release notes: ähnelt.
        /// </summary>
        public static string ReleaseNotes {
            get {
                return ResourceManager.GetString("ReleaseNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Remove from list ähnelt.
        /// </summary>
        public static string RemoveFileMenu {
            get {
                return ResourceManager.GetString("RemoveFileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Resets the zoom to the default value ähnelt.
        /// </summary>
        public static string ResetZoomToolTip {
            get {
                return ResourceManager.GetString("ResetZoomToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Renders the current song to a PDF file, saves it and runs it using your installed PDF viewer application ähnelt.
        /// </summary>
        public static string SaveAndRunPdfButtonTooltip {
            get {
                return ResourceManager.GetString("SaveAndRunPdfButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The document has to be saved first. ähnelt.
        /// </summary>
        public static string SaveBevorePdf {
            get {
                return ResourceManager.GetString("SaveBevorePdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Renders the current song to a PDF file and saves the result chord sheet file. The file will have the same name as the song file, but .PDF file extension ähnelt.
        /// </summary>
        public static string SavePdfButtonTooltip {
            get {
                return ResourceManager.GetString("SavePdfButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save the current song under a new name ähnelt.
        /// </summary>
        public static string SaveSongAsButtonTooltip {
            get {
                return ResourceManager.GetString("SaveSongAsButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save the current song to the original file ähnelt.
        /// </summary>
        public static string SaveSongButtonTooltip {
            get {
                return ResourceManager.GetString("SaveSongButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selects the preview mode to either be plain text or PDF ähnelt.
        /// </summary>
        public static string SetPreviewModeTooltip {
            get {
                return ResourceManager.GetString("SetPreviewModeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show logger ähnelt.
        /// </summary>
        public static string ShowLogger {
            get {
                return ResourceManager.GetString("ShowLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Song editor font ähnelt.
        /// </summary>
        public static string SongEditorFont {
            get {
                return ResourceManager.GetString("SongEditorFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Song editor font size ähnelt.
        /// </summary>
        public static string SongEditorFontSize {
            get {
                return ResourceManager.GetString("SongEditorFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort chord grids ähnelt.
        /// </summary>
        public static string SortChordGrids {
            get {
                return ResourceManager.GetString("SortChordGrids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Achordeon v{0} ähnelt.
        /// </summary>
        public static string StatusBarAppVersion {
            get {
                return ResourceManager.GetString("StatusBarAppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Marks the selected text to be a guitar tab, or removes the marks ähnelt.
        /// </summary>
        public static string TabUnTabSelectionTooltip {
            get {
                return ResourceManager.GetString("TabUnTabSelectionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text font ähnelt.
        /// </summary>
        public static string TextFont {
            get {
                return ResourceManager.GetString("TextFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text font size ähnelt.
        /// </summary>
        public static string TextFontSize {
            get {
                return ResourceManager.GetString("TextFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transposes the whole song by the specified amount of halftones ähnelt.
        /// </summary>
        public static string TransposeBoxTooltip {
            get {
                return ResourceManager.GetString("TransposeBoxTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transpose by halftones ähnelt.
        /// </summary>
        public static string TransposeByHalftones {
            get {
                return ResourceManager.GetString("TransposeByHalftones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reverts the last edits ähnelt.
        /// </summary>
        public static string UndoButtonTooltip {
            get {
                return ResourceManager.GetString("UndoButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Unpin from list ähnelt.
        /// </summary>
        public static string UnpinFileMenu {
            get {
                return ResourceManager.GetString("UnpinFileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unpin this item from the list. ähnelt.
        /// </summary>
        public static string UnpinToolTip {
            get {
                return ResourceManager.GetString("UnpinToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version: ähnelt.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Web site: ähnelt.
        /// </summary>
        public static string WebSite {
            get {
                return ResourceManager.GetString("WebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Increases the zoom ähnelt.
        /// </summary>
        public static string ZoomInToolTip {
            get {
                return ResourceManager.GetString("ZoomInToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Decreases the zoom ähnelt.
        /// </summary>
        public static string ZoomOutToolTip {
            get {
                return ResourceManager.GetString("ZoomOutToolTip", resourceCulture);
            }
        }
    }
}
